void reset_to_98(int *n);
void swap_int(int *a, int *b);
void _puts(char *str);
int _strlen(char *s);
int _putchar(char c);
void print_rev(char *s);
void puts2(char *str);
void rev_string(char *s);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
int _atoi(char *s);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
